weights: yolov5l.pt
cfg: ''
data: ./data/labels_person_military_seperate.yaml
hyp: data/hyp.scratch.yaml
epochs: 30
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: yolov5l_person_military_seperate
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
world_size: 1
global_rank: -1
save_dir: runs/train/yolov5l_person_military_seperate
total_batch_size: 8
